version: '3.1'
services:
    zoo1:
        image: zookeeper:3.4.10
        restart: always
        hostname: zoo1
        networks:
            - logsearch-network
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper:3.4.10
        restart: always
        hostname: zoo2
        networks:
            - logsearch-network
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper:3.4.10
        restart: always
        hostname: zoo3
        networks:
            - logsearch-network
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
networks:
     logsearch-network:
        driver: bridge